[workspace]
members = ["src/libkrun"]
exclude = ["examples/gtk_display"]
resolver = "2"

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"
lto = true

[patch.crates-io]
statx-sys = { git = "https://github.com/peppergrayxyz/statx-sys", rev = "c0cd9f6b654279be5b4e37fd06d17004687b2ed7" }
